version: '3'

volumes:
  redis: {}

services:
  django:
    container_name: habiapi_local_django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: habiapi_local_django
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local
    ports:
      - "8000:8000"
    depends_on:
      - "redis"
    command: /start
    restart: always

  redis:
    env_file:
      - ./.envs/.local
    image: "redis:6.0.7-alpine"
    ports:
      - '6379'
    volumes:
      - "redis:/data"
    restart: on-failure
