# Generated by Django 3.1.5 on 2021-06-27 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=32, null=True)),
                ('price', models.BigIntegerField()),
                ('description', models.TextField()),
                ('year', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'property',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('label', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'status',
                'unique_together': {('id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.status')),
            ],
            options={
                'db_table': 'status_history',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.ManyToManyField(related_name='status_histories', through='property.StatusHistory', to='property.Status'),
        ),
    ]
